M48
; DRILL file {KiCad 7.0.7} date Wed 06 Sep 2023 03:41:04 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-06T15:41:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X156.984Y-111.0
X156.984Y-115.0
T2
X114.5Y-105.5
X114.5Y-120.5
X159.5Y-105.5
X159.5Y-120.5
T0
M30
